// apps/demo-react/src/app/app.tsx
import { PdfSignReact, PdfSignReactRef } from '@shz/pdf-sign-react';
import { useRef, useState, useMemo, useCallback } from 'react';
import { SignatureField } from '@shz/pdf-sign-control';
import '../styles.css';
import { NewFieldState } from './types';
import { LeftPanel } from './components/LeftPanel';
import { RightPanel } from './components/RightPanel';
import { SignatureModal } from './components/SignatureModal';

export function App() {
  const pdfRef = useRef<PdfSignReactRef>(null);

  // App State
  const [pageInfo, setPageInfo] = useState('1 / ?');
  const [scale, setScale] = useState(100);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [fields, setFields] = useState<SignatureField[]>([]);

  // Generic Field Form State
  const [newField, setNewField] = useState<NewFieldState>({
    page: 1,
    x: 100,
    y: 100,
    width: 120,
    height: 80,
    type: 'text',
    content: 'Text Field',
    draggable: true,
    resizable: true,
    deletable: true
  });

  // Optimize Props to prevent re-renders
  const pdfLoaderOptions = useMemo(() => ({
    workerSrc: 'https://unpkg.com/pdfjs-dist@5.4.530/build/pdf.worker.min.mjs',
    cMapUrl: 'https://unpkg.com/pdfjs-dist@5.4.530/cmaps/',
    cMapPacked: true,
  }), []);

  const onPageChange = useCallback((page: number, total: number) => setPageInfo(`${page} / ${total}`), []);
  const onScaleChange = useCallback((s: number) => setScale(Math.round(s * 100)), []);
  const onError = useCallback((err: Error) => console.error('PDF Error:', err), []);
  const onFieldsChange = useCallback((newFields: SignatureField[]) => setFields([...newFields]), []);

  const handleConfirmSignature = (htmlContent: string) => {
    setNewField(prev => ({ ...prev, content: htmlContent }));
    setIsModalOpen(false);
  };

  const handleAddGenericField = () => {
    if (!pdfRef.current) return;
    const control = pdfRef.current.getControl();
    if (!control) return;

    if (newField.type === 'signature' && !newField.content) {
      alert('Please setup the signature first.');
      return;
    }
    if (newField.type === 'image' && !newField.content) {
      alert('Please upload an image first.');
      return;
    }

    const fieldId = `field-${Date.now()}`;
    const field: SignatureField = {
      id: fieldId,
      pageIndex: newField.page - 1,
      rect: {
        x: newField.x,
        y: newField.y,
        width: newField.width,
        height: newField.height
      },
      type: newField.type,
      content: newField.content,
      draggable: newField.draggable,
      resizable: newField.resizable,
      deletable: newField.deletable,
      style: {
        border: '1px solid #007bff',
        backgroundColor: 'rgba(0, 123, 255, 0.05)',
      }
    };

    control.addField(field).catch((err: Error) => alert(err.message));
  };

  const handleInputChange = (key: keyof NewFieldState, value: any) => {
    setNewField(prev => ({ ...prev, [key]: value }));
  };

  const handleUpdateField = (id: string, key: 'draggable' | 'resizable', value: boolean) => {
    setFields(prev => prev.map(f => f.id === id ? { ...f, [key]: value } : f));
  };

  const handleRemoveField = (id: string) => {
    setFields(prev => prev.filter(f => f.id !== id));
  };

  return (
    <>
      <header className="app-header">
        <span>PDF Sign Demo (React)</span>
      </header>

      <LeftPanel
        newField={newField}
        onChange={handleInputChange}
        onAdd={handleAddGenericField}
        onOpenSigModal={() => setIsModalOpen(true)}
        onClearSigContent={() => handleInputChange('content', '')}
      />

      <main className="main-content">
        <div className="toolbar">
          <div className="control-group">
            <button onClick={() => pdfRef.current?.previousPage()} title="Previous Page">◀</button>
            <span id="page-info" style={{ minWidth: '80px', textAlign: 'center' }}>{pageInfo}</span>
            <button onClick={() => pdfRef.current?.nextPage()} title="Next Page">▶</button>
          </div>

          <div className="divider"></div>

          <div className="control-group">
            <button onClick={() => pdfRef.current?.setScale((pdfRef.current?.getScale() ?? 1) - 0.25)} title="Zoom Out">−</button>
            <span id="zoom-info" style={{ minWidth: '50px', textAlign: 'center' }}>{scale}%</span>
            <button onClick={() => pdfRef.current?.setScale((pdfRef.current?.getScale() ?? 1) + 0.25)} title="Zoom In">+</button>
          </div>

          <div className="divider"></div>

          <div className="control-group">
            <select
              onChange={(e) => pdfRef.current?.setViewMode(e.target.value as 'scroll' | 'single')}
              defaultValue="scroll"
            >
              <option value="scroll">Scroll Mode</option>
              <option value="single">Single Page</option>
            </select>
          </div>
        </div>

        <div id="pdf-container">
          <PdfSignReact
            ref={pdfRef}
            src="https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf"
            viewMode="scroll"
            pdfLoaderOptions={pdfLoaderOptions}
            fields={fields}
            onPageChange={onPageChange}
            onScaleChange={onScaleChange}
            onError={onError}
            onFieldsChange={onFieldsChange}
          />
        </div>
      </main>

      <RightPanel
        fields={fields}
        onRemoveField={handleRemoveField}
        onUpdateField={handleUpdateField}
      />

      <SignatureModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onConfirm={handleConfirmSignature}
      />
    </>
  );
}

export default App;

// apps/demo-angular/src/app/app.ts
import { Component, ViewChild } from '@angular/core';
import { PdfSignAngularComponent } from '@shz/pdf-sign-angular';
import { PdfSignControl, PdfSignControlOptions, ViewMode } from '@shz/pdf-sign-control';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DomSanitizer } from '@angular/platform-browser';
import { LeftPanelComponent } from './components/left-panel/left-panel.component';
import { RightPanelComponent } from './components/right-panel/right-panel.component';
import { SignatureModalComponent } from './components/signature-modal/signature-modal.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, PdfSignAngularComponent, LeftPanelComponent, RightPanelComponent, SignatureModalComponent],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  @ViewChild(PdfSignAngularComponent) pdfComponent!: PdfSignAngularComponent;

  constructor(public sanitizer: DomSanitizer) { }

  pdfUrl = 'https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf';
  viewMode: ViewMode = 'scroll';

  pageInfo = '1 / ?';
  zoomInfo = '100%';
  currentDate = new Date().toLocaleDateString();

  pdfLoaderOptions: PdfSignControlOptions['pdfLoaderOptions'] = {
    workerSrc: 'https://unpkg.com/pdfjs-dist@5.4.530/build/pdf.worker.min.mjs',
    cMapUrl: 'https://unpkg.com/pdfjs-dist@5.4.530/cmaps/',
    cMapPacked: true
  };

  fields: any[] = [];
  isModalOpen = false;

  // Generic Field Form State
  newField = {
    page: 1,
    x: 100,
    y: 100,
    width: 120,
    height: 80,
    type: 'text',
    content: 'Text Field',
    draggable: true,
    resizable: true,
    deletable: true
  };

  handleAddField() {
    if (!this.pdfComponent) return;
    const control = this.pdfComponent.getControl();
    if (!control) return;

    const fieldId = `field-${Date.now()}`;
    const field = {
      id: fieldId,
      pageIndex: this.newField.page - 1,
      rect: {
        x: this.newField.x,
        y: this.newField.y,
        width: this.newField.width,
        height: this.newField.height
      },
      type: this.newField.type,
      content: this.newField.content,
      draggable: this.newField.draggable,
      resizable: this.newField.resizable,
      deletable: this.newField.deletable,
      style: {
        border: '1px solid #007bff',
        backgroundColor: 'rgba(0, 123, 255, 0.05)',
      }
    };

    control.addField(field as any).catch((err: Error) => alert(err.message));
  }

  onControlReady(control: PdfSignControl) {
    console.log('PDF Control ready:', control);
  }

  prevPage() {
    this.pdfComponent?.getControl()?.previousPage();
  }

  nextPage() {
    this.pdfComponent?.getControl()?.nextPage();
  }

  onError(error: any) {
    console.error('PDF Error:', error);
  }

  onPageChange(data: { page: number; total: number }) {
    this.pageInfo = `${data.page} / ${data.total}`;
  }

  onScaleChange(data: { scale: number }) {
    this.zoomInfo = `${Math.round(data.scale * 100)}%`;
  }

  onFieldsChange(fields: any[]) {
    this.fields = [...fields];
  }

  refreshFields() {
    // Trigger update if needed, usually references handled by component
    this.fields = [...this.fields];
  }

  removeField(id: string) {
    this.fields = this.fields.filter(f => f.id !== id);
  }

  // === Modal Logic ===
  openSignatureModal() {
    this.isModalOpen = true;
  }

  closeSignatureModal() {
    this.isModalOpen = false;
  }

  onSignatureSave(html: string) {
    this.newField.content = html;
    this.closeSignatureModal();
  }

  onClearSignatureContent() {
    this.newField.content = '';
  }

  // Zoom handlers  
  zoomIn() {
    const currentScale = this.pdfComponent?.getScale() ?? 1;
    this.pdfComponent?.setScale(currentScale + 0.25);
  }

  zoomOut() {
    const currentScale = this.pdfComponent?.getScale() ?? 1;
    this.pdfComponent?.setScale(currentScale - 0.25);
  }
}
