// packages/pdf-sign-angular/src/lib/pdf-sign-angular/pdf-sign-angular.ts

import { Component, ElementRef, ViewChild, OnInit, OnDestroy, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PdfSignControl, PdfSignControlOptions, ViewMode, SignatureField } from '@shznet/pdf-sign-control';

@Component({
  selector: 'lib-pdf-sign-angular',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './pdf-sign-angular.html',
  styleUrl: './pdf-sign-angular.css',
})
export class PdfSignAngularComponent implements OnInit, OnDestroy, OnChanges {
  @ViewChild('container', { static: true }) container!: ElementRef<HTMLDivElement>;

  /** PDF source URL or ArrayBuffer - auto-loads when provided */
  @Input() src?: string | Uint8Array | ArrayBuffer;

  /** Initial view mode: 'scroll' or 'single' */
  @Input() viewMode?: ViewMode;

  /** Initial fields */
  @Input() fields?: SignatureField[];

  /** PDF.js loader options */
  @Input() pdfLoaderOptions?: PdfSignControlOptions['pdfLoaderOptions'];

  /** Emitted when control is ready */
  @Output() ready = new EventEmitter<PdfSignControl>();

  /** Emitted when PDF is loaded */
  @Output() loaded = new EventEmitter<void>();

  /** Emitted when page changes */
  @Output() pageChange = new EventEmitter<{ page: number; total: number }>();

  /** Emitted when scale changes */
  @Output() scaleChange = new EventEmitter<{ scale: number }>();

  /** Emitted on error */
  @Output() error = new EventEmitter<Error>();

  /** Emitted when a field is added */
  @Output() fieldAdd = new EventEmitter<SignatureField>();

  /** Emitted when a field is removed */
  @Output() fieldRemove = new EventEmitter<{ fieldId: string }>();

  /** Emitted when a field is updated */
  @Output() fieldUpdate = new EventEmitter<{ fieldId: string, updates: Partial<SignatureField> }>();

  /** Emitted when any field changes (add/remove/update) */
  @Output() fieldsChange = new EventEmitter<SignatureField[]>();

  private control: PdfSignControl | null = null;

  ngOnInit() {
    if (this.container) {
      this.control = new PdfSignControl({
        container: this.container.nativeElement,
        viewMode: this.viewMode,
        pdfLoaderOptions: this.pdfLoaderOptions,
        fields: this.fields
      });

      // Setup event listeners
      this.control.on('page:change', (data: { page: number; total: number }) => {
        this.pageChange.emit(data);
      });

      this.control.on('scale:change', (data: { scale: number }) => {
        this.scaleChange.emit(data);
      });

      // Field Events
      this.control.on('field:add', (field: SignatureField) => {
        this.fieldAdd.emit(field);
      });
      this.control.on('field:remove', (data: { fieldId: string }) => {
        this.fieldRemove.emit(data);
      });
      this.control.on('field:update', (data: { fieldId: string, updates: Partial<SignatureField> }) => {
        this.fieldUpdate.emit(data);
      });
      this.control.on('fields:change', (fields: SignatureField[]) => {
        this.fieldsChange.emit(fields);
      });

      this.ready.emit(this.control);

      // Auto-load if src provided
      if (this.src) {
        this.loadPdf(this.src);
      }
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['src'] && !changes['src'].firstChange && this.src) {
      this.loadPdf(this.src);
    }
    if (changes['viewMode'] && !changes['viewMode'].firstChange && this.viewMode) {
      this.control?.setViewMode(this.viewMode);
    }
    if (changes['fields'] && !changes['fields'].firstChange && this.fields) {
      const currentFields = this.control?.getFields();
      if (JSON.stringify(currentFields) === JSON.stringify(this.fields)) {
        return;
      }
      this.control?.setFields(this.fields);
    }
  }

  ngOnDestroy() {
    if (this.control) {
      this.control.destroy();
      this.control = null;
    }
  }

  private loadPdf(source: string | Uint8Array | ArrayBuffer) {
    this.control?.load(source)
      .then(() => this.loaded.emit())
      .catch((err) => this.error.emit(err));
  }

  // Public API methods

  /** Get the underlying PdfSignControl instance */
  getControl(): PdfSignControl | null {
    return this.control;
  }

  /** Load a PDF from URL or ArrayBuffer */
  load(source: string | Uint8Array | ArrayBuffer): Promise<void> {
    return this.control?.load(source) ?? Promise.reject('Control not initialized');
  }

  /** Navigate to specific page */
  goToPage(page: number): void {
    this.control?.goToPage(page);
  }

  /** Go to next page */
  nextPage(): void {
    this.control?.nextPage();
  }

  /** Go to previous page */
  previousPage(): void {
    this.control?.previousPage();
  }

  /** Get current page number */
  getCurrentPage(): number {
    return this.control?.getCurrentPage() ?? 1;
  }

  /** Get total pages */
  getTotalPages(): number {
    return this.control?.getTotalPages() ?? 0;
  }

  /** Set zoom scale */
  setScale(scale: number): void {
    this.control?.setScale(scale);
  }

  /** Get current zoom scale */
  getScale(): number {
    return this.control?.getScale() ?? 1.0;
  }

  /** Set view mode */
  setViewMode(mode: ViewMode): Promise<void> {
    return this.control?.setViewMode(mode) ?? Promise.resolve();
  }

  /** Get current view mode */
  getViewMode(): ViewMode {
    return this.control?.getViewMode() ?? 'scroll';
  }

  // Field Management Wrappers

  addField(field: any): void {
    this.control?.addField(field);
  }

  removeField(fieldId: string): void {
    this.control?.removeField(fieldId);
  }

  updateField(fieldId: string, updates: any): void {
    this.control?.updateField(fieldId, updates);
  }

  setFields(fields: any[]): void {
    this.control?.setFields(fields);
  }
}

// packages/pdf-sign-react/src/lib/pdf-sign-react.tsx
import { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import { PdfSignControl, PdfSignControlOptions, ViewMode, SignatureField } from '@shz/pdf-sign-control';

export interface PdfSignReactRef {
  /** Get the underlying PdfSignControl instance */
  getControl(): PdfSignControl | null;
  /** Load a PDF from URL or ArrayBuffer */
  load(source: string | Uint8Array | ArrayBuffer): Promise<void>;
  /** Navigate to specific page */
  goToPage(page: number): void;
  /** Go to next page */
  nextPage(): void;
  /** Go to previous page */
  previousPage(): void;
  /** Get current page number */
  getCurrentPage(): number;
  /** Get total pages */
  getTotalPages(): number;
  /** Set zoom scale */
  setScale(scale: number): void;
  /** Get current zoom scale */
  getScale(): number;
  /** Set view mode */
  setViewMode(mode: ViewMode): Promise<void>;
  /** Get current view mode */
  getViewMode(): ViewMode;
}

export interface PdfSignReactProps {
  /** PDF source URL or ArrayBuffer - auto-loads when provided */
  src?: string | Uint8Array | ArrayBuffer;
  /** Initial view mode: 'scroll' or 'single' */
  viewMode?: ViewMode;
  /** Enable gesture zoom (Ctrl+scroll, pinch) - default: true */
  zoomable?: boolean;
  /** PDF.js loader options */
  pdfLoaderOptions?: PdfSignControlOptions['pdfLoaderOptions'];
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Callback when control is ready */
  onReady?: (control: PdfSignControl) => void;
  /** Callback when PDF is loaded */
  onLoad?: () => void;
  /** Callback when page changes */
  onPageChange?: (page: number, total: number) => void;
  /** Callback when scale changes */
  onScaleChange?: (scale: number) => void;
  /** Callback on error */
  onError?: (error: Error) => void;

  /** Initial fields */
  fields?: SignatureField[];

  /** Callback when a field is added */
  onFieldAdd?: (field: SignatureField) => void;
  /** Callback when a field is removed */
  onFieldRemove?: (data: { fieldId: string }) => void;
  /** Callback when a field is updated */
  onFieldUpdate?: (data: { fieldId: string, updates: Partial<SignatureField> }) => void;
  /** Callback when any field changes (add/remove/update) */
  onFieldsChange?: (fields: SignatureField[]) => void;
}

export const PdfSignReact = forwardRef<PdfSignReactRef, PdfSignReactProps>((props, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const controlRef = useRef<PdfSignControl | null>(null);

  useImperativeHandle(ref, () => ({
    getControl: () => controlRef.current,
    load: async (source) => {
      if (controlRef.current) {
        await controlRef.current.load(source);
      }
    },
    goToPage: (page) => controlRef.current?.goToPage(page),
    nextPage: () => controlRef.current?.nextPage(),
    previousPage: () => controlRef.current?.previousPage(),
    getCurrentPage: () => controlRef.current?.getCurrentPage() ?? 1,
    getTotalPages: () => controlRef.current?.getTotalPages() ?? 0,
    setScale: (scale) => controlRef.current?.setScale(scale),
    getScale: () => controlRef.current?.getScale() ?? 1.0,
    setViewMode: async (mode) => {
      if (controlRef.current) {
        await controlRef.current.setViewMode(mode);
      }
    },
    getViewMode: () => controlRef.current?.getViewMode() ?? 'scroll',
  }));

  useEffect(() => {
    if (!containerRef.current || controlRef.current) return;

    controlRef.current = new PdfSignControl({
      container: containerRef.current,
      viewMode: props.viewMode,
      pdfLoaderOptions: props.pdfLoaderOptions,
      fields: props.fields,
    });

    // Setup event listeners
    if (props.onPageChange) {
      controlRef.current.on('page:change', (data: { page: number; total: number }) => {
        props.onPageChange?.(data.page, data.total);
      });
    }

    if (props.onScaleChange) {
      controlRef.current.on('scale:change', (data: { scale: number }) => {
        props.onScaleChange?.(data.scale);
      });
    }

    // Field Events
    if (props.onFieldAdd) {
      controlRef.current.on('field:add', (field: any) => props.onFieldAdd?.(field));
    }
    if (props.onFieldRemove) {
      controlRef.current.on('field:remove', (data: any) => props.onFieldRemove?.(data));
    }
    if (props.onFieldUpdate) {
      controlRef.current.on('field:update', (data: any) => props.onFieldUpdate?.(data));
    }
    if (props.onFieldsChange) {
      controlRef.current.on('fields:change', (fields: any[]) => props.onFieldsChange?.(fields));
    }

    if (props.onReady) {
      props.onReady(controlRef.current);
    }

    return () => {
      controlRef.current?.destroy();
      controlRef.current = null;
    };
  }, []);

  // Handle src changes
  useEffect(() => {
    if (controlRef.current && props.src) {
      controlRef.current.load(props.src)
        .then(() => props.onLoad?.())
        .catch((error) => props.onError?.(error));
    }
  }, [props.src]);

  // Handle viewMode changes
  useEffect(() => {
    if (controlRef.current && props.viewMode) {
      controlRef.current.setViewMode(props.viewMode);
    }
  }, [props.viewMode]);

  // Handle fields changes
  useEffect(() => {
    if (controlRef.current && props.fields) {
      // Loop Prevention: Check if fields are actually different
      const currentFields = controlRef.current.getFields();

      if (JSON.stringify(currentFields) === JSON.stringify(props.fields)) {
        return;
      }
      controlRef.current.setFields(props.fields);
    }
  }, [props.fields]);

  return <div ref={containerRef} className={props.className} style={{ width: '100%', height: '100%', ...props.style }} />;
});

// Re-export types
export type { ViewMode } from '@shz/pdf-sign-control';
