// apps/demo-react/src/app/components/SignatureModal.tsx
import React, { useState, useEffect, useRef } from 'react';
import SignaturePad from 'signature_pad';
import { SignatureGenerator, SignatureConfig } from '../signature-generator';
import { SignaturePreview } from './SignaturePreview';

interface SignatureModalProps {
    isOpen: boolean;
    onClose: () => void;
    onConfirm: (htmlContent: string) => void;
}

export const SignatureModal: React.FC<SignatureModalProps> = ({ isOpen, onClose, onConfirm }) => {
    if (!isOpen) return null;

    // State
    const [activeTab, setActiveTab] = useState<'drawing' | 'certName' | 'image'>('drawing');
    const [sigLayout, setSigLayout] = useState<'horizontal' | 'vertical'>('horizontal');
    const [sigFontSize, setSigFontSize] = useState(5);
    const [infoLines, setInfoLines] = useState<string[]>(['Signed by: Alice', 'Date:']);
    const [certName, setCertName] = useState('');
    const [drawingColor, setDrawingColor] = useState('#2563eb');
    const [penWidth, setPenWidth] = useState(1);
    const [selectedImage, setSelectedImage] = useState<string | null>(null);

    // Refs
    const sigCanvasRef = useRef<HTMLCanvasElement>(null);
    const sigPadRef = useRef<SignaturePad | null>(null);

    // Force update for ref changes or canvas drawing
    const [, setTick] = useState(0);

    // Helper
    const getVisualContent = (): string => {
        if (activeTab === 'certName') return certName || 'Your Name';
        if (activeTab === 'image') return selectedImage || '';
        if (activeTab === 'drawing') return sigPadRef.current?.toDataURL() || '';
        return '';
    };

    // Derived Config
    const config: SignatureConfig = {
        layout: sigLayout,
        fontSize: sigFontSize,
        infoLines: [...infoLines],
        visualType: activeTab === 'image' ? 'image' : (activeTab === 'certName' ? 'text' : 'drawing'),
        visualContent: getVisualContent()
    };

    const updatePreview = () => {
        setTick(t => t + 1);
    };

    // Initialize Signature Pad
    useEffect(() => {
        if (isOpen && activeTab === 'drawing' && sigCanvasRef.current) {
            setTimeout(() => {
                if (!sigCanvasRef.current) return;

                if (!sigPadRef.current) {
                    sigPadRef.current = new SignaturePad(sigCanvasRef.current, {
                        backgroundColor: 'rgba(255, 255, 255, 0)',
                        penColor: drawingColor,
                        minWidth: penWidth,
                        maxWidth: penWidth * 2.5
                    });

                    sigPadRef.current.addEventListener('endStroke', () => updatePreview());
                }

                const canvas = sigCanvasRef.current;
                const ratio = Math.max(window.devicePixelRatio || 1, 1);
                canvas.width = canvas.offsetWidth * ratio;
                canvas.height = canvas.offsetHeight * ratio;
                canvas.getContext('2d')?.scale(ratio, ratio);

                sigPadRef.current.clear();
                updatePreview();
            }, 50);
        }
    }, [isOpen, activeTab]);

    // Update Pen Style
    useEffect(() => {
        if (sigPadRef.current) {
            sigPadRef.current.penColor = drawingColor;
            sigPadRef.current.minWidth = penWidth;
            sigPadRef.current.maxWidth = penWidth * 2.5;
        }
    }, [drawingColor, penWidth]);

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const reader = new FileReader();
            reader.onload = (ev) => {
                setSelectedImage(ev.target?.result as string);
            };
            reader.readAsDataURL(e.target.files[0]);
        }
    };

    const handleConfirm = () => {
        // Validate
        if (activeTab === 'drawing' && sigPadRef.current?.isEmpty()) {
            alert('Please draw a signature first.');
            return;
        }
        if (activeTab === 'certName' && !certName.trim()) {
            alert('Please enter a name.');
            return;
        }
        if (activeTab === 'image' && !selectedImage) {
            alert('Please select an image.');
            return;
        }

        const generator = new SignatureGenerator();
        const html = generator.generate(config);
        onConfirm(html);
    };

    return (
        <div className="modal-overlay">
            <div className="modal-content sig-modal">
                <div className="sig-modal-header">
                    <h3>Signature Configuration</h3>
                    <button className="close-btn" onClick={onClose}>×</button>
                </div>

                <div className="sig-modal-body">
                    <div className="sig-modal-content">
                        <div className="sig-left-panel">
                            <div className="sig-tabs">
                                <div className={`sig-tab ${activeTab === 'drawing' ? 'active' : ''}`} onClick={() => setActiveTab('drawing')}>Draw</div>
                                <div className={`sig-tab ${activeTab === 'certName' ? 'active' : ''}`} onClick={() => setActiveTab('certName')}>Name</div>
                                <div className={`sig-tab ${activeTab === 'image' ? 'active' : ''}`} onClick={() => setActiveTab('image')}>Image</div>
                            </div>

                            {/* Drawing */}
                            <div className={`tab-content ${activeTab !== 'drawing' ? 'hidden' : ''}`}>
                                <div className="signature-pad-container">
                                    <canvas ref={sigCanvasRef} className="signature-pad"></canvas>
                                </div>
                                <div className="sig-controls">
                                    <div className="control-row">
                                        <button className={`color-btn ${drawingColor === '#2563eb' ? 'active' : ''}`} style={{ background: '#2563eb' }} onClick={() => setDrawingColor('#2563eb')}></button>
                                        <button className={`color-btn ${drawingColor === '#1f2937' ? 'active' : ''}`} style={{ background: '#1f2937' }} onClick={() => setDrawingColor('#1f2937')}></button>
                                        <button className={`color-btn ${drawingColor === '#dc2626' ? 'active' : ''}`} style={{ background: '#dc2626' }} onClick={() => setDrawingColor('#dc2626')}></button>
                                    </div>
                                    <div className="control-row">
                                        <span className="control-label" style={{ marginRight: '10px', fontSize: '13px', color: '#6b7280' }}>Stroke</span>
                                        <button className={`pen-btn ${penWidth === 1 ? 'active' : ''}`} onClick={() => setPenWidth(1)} style={{ width: '8px', height: '8px' }}></button>
                                        <button className={`pen-btn ${penWidth === 2.5 ? 'active' : ''}`} onClick={() => setPenWidth(2.5)} style={{ width: '12px', height: '12px', marginLeft: '10px' }}></button>
                                    </div>
                                </div>
                            </div>

                            {/* Name */}
                            <div className={`tab-content ${activeTab !== 'certName' ? 'hidden' : ''}`}>
                                <div className="certname-input-container">
                                    <input type="text" className="certname-input" placeholder="Enter your name" value={certName} onChange={e => setCertName(e.target.value)} />
                                </div>
                            </div>

                            {/* Image */}
                            <div className={`tab-content ${activeTab !== 'image' ? 'hidden' : ''}`}>
                                <div className="image-upload-container" onClick={() => document.getElementById('react-sig-upload')?.click()}>
                                    <input type="file" id="react-sig-upload" hidden accept="image/*" onChange={handleImageUpload} />
                                    {selectedImage ? (
                                        <div className="image-preview"><img src={selectedImage} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} /></div>
                                    ) : (
                                        <div className="upload-placeholder">
                                            <div className="upload-icon">☁️</div>
                                            <div>Click to upload</div>
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="option-group" style={{ marginTop: '20px' }}>
                                <div className="option-label">Layout</div>
                                <div className="toggle-group">
                                    <button className={`toggle-btn ${sigLayout === 'horizontal' ? 'active' : ''}`} onClick={() => setSigLayout('horizontal')}>Horizontal</button>
                                    <button className={`toggle-btn ${sigLayout === 'vertical' ? 'active' : ''}`} onClick={() => setSigLayout('vertical')}>Vertical</button>
                                </div>
                            </div>
                        </div>

                        <div className="sig-right-panel">
                            <div className="option-group">
                                <div className="option-label">Display Content</div>
                                <div className="info-lines-list">
                                    {infoLines.map((line, i) => (
                                        <div key={i} className="info-line-item">
                                            <input type="text" className="info-line-input" value={line} onChange={e => {
                                                const newLines = [...infoLines];
                                                newLines[i] = e.target.value;
                                                setInfoLines(newLines);
                                            }} />
                                            <button className="remove-line-btn" onClick={() => setInfoLines(infoLines.filter((_, idx) => idx !== i))}>×</button>
                                        </div>
                                    ))}
                                    <button className="add-line-btn" onClick={() => setInfoLines([...infoLines, ''])}>+ Add Line</button>
                                </div>
                            </div>

                            <div className="option-group">
                                <div className="option-label">Font Size</div>
                                <input type="range" min="3" max="9" className="slider" value={sigFontSize} onChange={e => setSigFontSize(parseInt(e.target.value))} />
                            </div>

                            <div className="option-group">
                                <div className="option-label">Preview</div>
                                <div className="sig-preview">
                                    <SignaturePreview config={config} />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="modal-actions">
                    <button className="btn-secondary" onClick={onClose}>Cancel</button>
                    <button className="sig-confirm-btn" onClick={handleConfirm}>Confirm</button>
                </div>
            </div>
        </div>
    );
};

// apps/demo-angular/src/app/components/signature-modal/signature-modal.component.ts
import { Component, ElementRef, EventEmitter, Input, NgZone, Output, ViewChild, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DomSanitizer } from '@angular/platform-browser';
import SignaturePad from 'signature_pad';
import { SignatureConfig, SignatureGenerator } from '../../signature-generator';
import { SignaturePreviewComponent } from '../signature-preview/signature-preview.component';

@Component({
    selector: 'app-signature-modal',
    standalone: true,
    imports: [CommonModule, FormsModule, SignaturePreviewComponent],
    templateUrl: './signature-modal.component.html',
    styles: []
})
export class SignatureModalComponent {
    @Input() isOpen = false;
    @Output() close = new EventEmitter<void>();
    @Output() save = new EventEmitter<string>();

    @ViewChild('signatureCanvas') signatureCanvas!: ElementRef<HTMLCanvasElement>;

    // State
    activeTab: 'drawing' | 'certName' | 'image' = 'drawing';
    signaturePad?: SignaturePad;

    // Config
    sigLayout: 'horizontal' | 'vertical' = 'horizontal';
    sigFontSize = 5;
    infoLines: string[] = ['Signed by: Alice', 'Date:'];
    certName = '';
    drawingColor = '#2563eb';
    penWidth = 1;
    selectedImage: string | null = null;

    // Preview Config for Child Component
    previewConfig?: SignatureConfig;

    private sigGen = new SignatureGenerator();

    constructor(public sanitizer: DomSanitizer, private zone: NgZone, private cdr: ChangeDetectorRef) { }

    ngOnInit() {
        this.updatePreview();
    }

    ngOnChanges() {
        if (this.isOpen) {
            this.updatePreview();
            // Defer initialization to ensure ViewChild is available
            setTimeout(() => {
                this.initSignaturePad();
                this.updatePreview();
            }, 100);
        }
    }

    onClose() {
        this.close.emit();
    }

    onSave() {
        if (this.activeTab === 'drawing' && this.signaturePad?.isEmpty()) {
            alert('Please draw a signature first.');
            return;
        }
        if (this.activeTab === 'certName' && !this.certName.trim()) {
            alert('Please enter a name.');
            return;
        }
        if (this.activeTab === 'image' && !this.selectedImage) {
            alert('Please select an image.');
            return;
        }

        const config: SignatureConfig = {
            layout: this.sigLayout,
            fontSize: this.sigFontSize,
            infoLines: [...this.infoLines],
            visualType: this.activeTab === 'image' ? 'image' : (this.activeTab === 'certName' ? 'text' : 'drawing'),
            visualContent: this.getVisualContent()
        };
        const finalHtml = this.sigGen.generate(config);
        this.save.emit(finalHtml);
        this.onClose();
    }

    switchTab(tab: 'drawing' | 'certName' | 'image') {
        this.activeTab = tab;
        if (tab === 'drawing') {
            setTimeout(() => this.resizeCanvas(), 50);
        }
        this.updatePreview();
    }

    // Info Lines
    addInfoLine() {
        this.infoLines.push('');
        this.updatePreview();
    }

    removeInfoLine(index: number) {
        this.infoLines.splice(index, 1);
        this.updatePreview();
    }

    updateInfoLine(index: number, event: Event) {
        const val = (event.target as HTMLInputElement).value;
        this.infoLines[index] = val;
        this.updatePreview();
    }

    trackByIndex(index: number, obj: any): any {
        return index;
    }

    // Signature Pad
    initSignaturePad() {
        if (this.signatureCanvas && !this.signaturePad) {
            this.signaturePad = new SignaturePad(this.signatureCanvas.nativeElement, {
                backgroundColor: 'rgba(255, 255, 255, 0)',
                penColor: this.drawingColor,
                minWidth: this.penWidth,
                maxWidth: this.penWidth + 1.5
            });

            this.signaturePad.addEventListener('endStroke', () => {
                this.zone.run(() => this.updatePreview());
            });
            this.resizeCanvas();
        }
    }

    resizeCanvas() {
        const canvas = this.signatureCanvas?.nativeElement;
        if (canvas && this.signaturePad) {
            const ratio = Math.max(window.devicePixelRatio || 1, 1);
            canvas.width = canvas.offsetWidth * ratio;
            canvas.height = canvas.offsetHeight * ratio;
            canvas.getContext('2d')?.scale(ratio, ratio);
            this.signaturePad.clear();
        }
    }

    setDrawingColor(color: string) {
        this.drawingColor = color;
        if (this.signaturePad) {
            this.signaturePad.penColor = color;
        }
    }

    setPenWidth(width: number) {
        this.penWidth = width;
        if (this.signaturePad) {
            this.signaturePad.minWidth = width;
            this.signaturePad.maxWidth = width + 1.5;
        }
    }

    // Image Upload
    triggerImageUpload() {
        document.getElementById('sig-image-upload-comp')?.click();
    }

    onImageSelected(event: Event) {
        const input = event.target as HTMLInputElement;
        if (input.files && input.files[0]) {
            const reader = new FileReader();
            reader.onload = (e) => {
                this.selectedImage = e.target?.result as string;
                this.updatePreview();
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    // Generator
    updatePreview() {
        this.previewConfig = {
            layout: this.sigLayout,
            fontSize: this.sigFontSize,
            infoLines: [...this.infoLines],
            visualType: this.activeTab === 'image' ? 'image' : (this.activeTab === 'certName' ? 'text' : 'drawing'),
            visualContent: this.getVisualContent()
        };
        this.cdr.detectChanges();
    }

    getVisualContent(): string {
        if (this.activeTab === 'certName') return this.certName || 'Your Name';
        if (this.activeTab === 'image') return this.selectedImage || '';
        if (this.activeTab === 'drawing') return this.signaturePad?.toDataURL() || '';
        return '';
    }
}

<div class="modal-overlay" *ngIf="isOpen">
    <div class="modal-content sig-modal">
        <div class="sig-modal-header">
            <h3>Signature Configuration</h3>
            <button class="close-btn" (click)="onClose()">×</button>
        </div>

        <div class="sig-modal-body">
            <div class="sig-modal-content">
                <!-- Left Panel -->
                <div class="sig-left-panel">
                    <!-- Tabs -->
                    <div class="sig-tabs">
                        <div class="sig-tab" [class.active]="activeTab === 'drawing'" (click)="switchTab('drawing')">
                            Draw</div>
                        <div class="sig-tab" [class.active]="activeTab === 'certName'" (click)="switchTab('certName')">
                            Name</div>
                        <div class="sig-tab" [class.active]="activeTab === 'image'" (click)="switchTab('image')">Image
                        </div>
                    </div>
                    <!-- Drawing Tab -->
                    <div class="tab-content" [class.hidden]="activeTab !== 'drawing'">
                        <div class="signature-pad-container">
                            <canvas #signatureCanvas class="signature-pad"></canvas>
                        </div>

                        <div class="sig-controls">
                            <div class="control-row">
                                <button class="color-btn" style="background:#2563eb"
                                    [class.active]="drawingColor === '#2563eb'"
                                    (click)="setDrawingColor('#2563eb')"></button>
                                <button class="color-btn" style="background:#000000"
                                    [class.active]="drawingColor === '#000000'"
                                    (click)="setDrawingColor('#000000')"></button>
                                <button class="color-btn" style="background:#dc2626"
                                    [class.active]="drawingColor === '#dc2626'"
                                    (click)="setDrawingColor('#dc2626')"></button>
                            </div>
                            <div class="control-row">
                                <button class="pen-btn" [class.active]="penWidth === 1" (click)="setPenWidth(1)"
                                    style="width:24px; height:24px; display:flex; align-items:center; justify-content:center;">
                                    <div style="width:4px; height:4px; background:white; border-radius:50%;"></div>
                                </button>
                                <button class="pen-btn" [class.active]="penWidth === 3" (click)="setPenWidth(3)"
                                    style="width:28px; height:28px; display:flex; align-items:center; justify-content:center;">
                                    <div style="width:8px; height:8px; background:white; border-radius:50%;"></div>
                                </button>
                            </div>
                        </div>
                    </div>

                    <!-- Name Tab -->
                    <div class="tab-content" [class.hidden]="activeTab !== 'certName'">
                        <div class="certname-input-container">
                            <input type="text" class="certname-input" placeholder="Enter your name"
                                [(ngModel)]="certName" (input)="updatePreview()">
                        </div>
                    </div>

                    <!-- Image Tab -->
                    <div class="tab-content" [class.hidden]="activeTab !== 'image'">
                        <div class="image-upload-container" (click)="triggerImageUpload()">
                            <input type="file" id="sig-image-upload-comp" hidden accept="image/*"
                                (change)="onImageSelected($event)">
                            <div class="image-preview" *ngIf="selectedImage; else uploadPlaceholder">
                                <img [src]="selectedImage" style="max-width:100%; max-height:100%; object-fit:contain;">
                            </div>
                            <ng-template #uploadPlaceholder>
                                <div class="upload-placeholder">
                                    <div class="upload-icon">☁️</div>
                                    <div>Click to upload</div>
                                    <div style="font-size:12px; margin-top:4px;">(PNG, JPG, SVG)</div>
                                </div>
                            </ng-template>
                        </div>
                    </div>

                    <!-- Layout Options -->
                    <div class="option-group" style="margin-top: 20px;">
                        <div class="option-label">Layout</div>
                        <div class="toggle-group">
                            <button class="toggle-btn" [class.active]="sigLayout === 'horizontal'"
                                (click)="sigLayout = 'horizontal'; updatePreview()">Horizontal</button>
                            <button class="toggle-btn" [class.active]="sigLayout === 'vertical'"
                                (click)="sigLayout = 'vertical'; updatePreview()">Vertical</button>
                        </div>
                    </div>
                </div>

                <!-- Right Panel -->
                <div class="sig-right-panel">

                    <!-- Information Lines -->
                    <div class="option-group">
                        <div class="option-label">Display Content</div>
                        <div class="info-lines-list">
                            <div *ngFor="let line of infoLines; let i = index; trackBy: trackByIndex"
                                class="info-line-item">
                                <input type="text" class="info-line-input" [value]="line"
                                    (input)="updateInfoLine(i, $event)">
                                <button class="remove-line-btn" (click)="removeInfoLine(i)">×</button>
                            </div>
                            <button class="add-line-btn" (click)="addInfoLine()">+ Add Line</button>
                        </div>
                    </div>

                    <!-- Font Size -->
                    <div class="option-group">
                        <div class="option-label">Font Size</div>
                        <input type="range" min="3" max="9" class="slider" [(ngModel)]="sigFontSize"
                            (input)="updatePreview()">
                    </div>

                    <!-- Preview -->
                    <div class="option-group">
                        <div class="option-label">Preview</div>
                        <div class="sig-preview">
                            <app-signature-preview [config]="previewConfig"></app-signature-preview>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="modal-actions">
            <button class="btn-secondary" (click)="onClose()">Cancel</button>
            <button class="sig-confirm-btn" (click)="onSave()">Confirm</button>
        </div>
    </div>
</div>
